### ISSUE TITLE
latest version issue with Menu Companions

### ISSUE THREAD

**Issue by Wedge1453** [Thelnfamous1/Dungeons-Mobs#35]
https://github.com/Fuzss/menucompanions/issues/12

**Comment by Wedge1453** [comment]
ava.lang.IllegalStateException: Tag dungeons_mobs:converts_in_water used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131)
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142)
	at net.minecraft.entity.EntityType.func_220341_a(EntityType.java:542)
	at com.infamous.dungeons_mobs.capabilities.convertible.ConvertibleHelper.convertsInWater(ConvertibleHelper.java:86)
	at com.infamous.dungeons_mobs.MobEvents.onAttachEntityCapabilities(MobEvents.java:94)
	at net.minecraftforge.eventbus.ASMEventHandler_344_MobEvents_onAttachEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)

**Comment by BraveCaperCat** [comment]
Ok............................................................................................................................................................................................................What is "Menu companions"

**Comment by Patrigan** [comment]
Should be fixed in latest betas
