### ISSUE TITLE
I keep having this crash

### ISSUE THREAD

**Issue by f202k** [Thelnfamous1/Dungeons-Mobs#39]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/22/21 10:02 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.entity.projectile.ProjectileHelper.getWeaponHoldingHand(Lnet/minecraft/entity/LivingEntity;Ljava/util/function/Predicate;)Lnet/minecraft/util/Hand;
	at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_85036_m(SunkenSkeletonEntity.java:166) ~[?:1.0.10] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_184201_a(AbstractSkeletonEntity.java:203) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4,re:mixin,pl:accesstransformer:B}
	at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_180481_a(SunkenSkeletonEntity.java:192) ~[?:1.0.10] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_213386_a(AbstractSkeletonEntity.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$21302/132733937.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$20679/1132734006.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_85036_m(SunkenSkeletonEntity.java:166) ~[?:1.0.10] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_184201_a(AbstractSkeletonEntity.java:203) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4,re:mixin,pl:accesstransformer:B}
	at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_180481_a(SunkenSkeletonEntity.java:192) ~[?:1.0.10] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_213386_a(AbstractSkeletonEntity.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$21302/132733937.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['f202k'/1754, l='ServerLevel[E]', x=-121.36, y=58.92, z=-100.40]]
	Chunk stats: ServerChunkCache: 2652
	Level dimension: minecraft:overworld
	Level spawn location: World: (-195,63,-4), Chunk: (at 13,3,12 in -13,-1; contains blocks -208,0,-16 to -193,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5503 game time, 5503 day time
	Level name: E
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 36590 (now: false), thunder time: 55453 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$20679/1132734006.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3059250176 bytes (2917 MB) / 6039797760 bytes (5760 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |NOSIGNATURE
		DungeonsMod-1.16.3-1.3.20.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.3.20       |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.101.jar                          |Just Enough Items             |jei                           |7.7.0.101           |DONE      |NOSIGNATURE
		timeless_and_classic_4.0.0_RELEASE.jar            |Timeless and Classic Mod Addon|timeless_and_classic          |0.3                 |DONE      |NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.5-1.0.10.jar                   |Dungeons Mobs                 |dungeons_mobs                 |1.0.10              |DONE      |NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |DONE      |NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |NOSIGNATURE
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |NOSIGNATURE
		modernlife-1.16.5-1.13.jar                        |Modern Life                   |modernlife                    |1.16.5-1.13         |DONE      |NOSIGNATURE
		citadel-1.7.1-1.16.5.jar                          |Citadel                       |citadel                       |1.7.1               |DONE      |NOSIGNATURE
		alexsmobs-1.11.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.0              |DONE      |NOSIGNATURE
		Artifacts-1.16.5-2.9.2.jar                        |Artifacts                     |artifacts                     |1.16.5-2.9.2        |DONE      |NOSIGNATURE
		untamedwilds-1.16.5-1.3.1.jar                     |Untamed Wilds                 |untamedwilds                  |1.1.0               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		additional-guns-0.2.0-1.16.5.jar                  |Additional Guns               |additionalguns                |0.2.0               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |NOSIGNATURE
		outvoted-1.16.5-1.2.4.jar                         |Outvoted                      |outvoted                      |1.2.4               |DONE      |NOSIGNATURE
		iceandfire-2.1.8-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.8-1.16.5        |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		gunswithoutroses-1.16.5-1.0.9.jar                 |Guns Without Roses            |gunswithoutroses              |1.0.9               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.16.5-4.0.482-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |NOSIGNATURE
		subwild-1.2.1.jar                                 |Subterranean Wilderness       |subwild                       |1.2.1               |DONE      |NOSIGNATURE
		meetyourfight-1.16.5-1.1.2.jar                    |Meet Your Fight               |meetyourfight                 |1.1.2               |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |NOSIGNATURE
		dungeonsarise1.16.5-1.2.72a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.72a             |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.0-135.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.0-135    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		greekfantasy-16.4.17.jar                          |Greek Fantasy                 |greekfantasy                  |16.4.17             |DONE      |NOSIGNATURE
		Exotic+Crittes+1.16Experimental1.13.jar           |Exotic Critters               |experimental_m                |1.0.0               |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		AmbientWorld-1.3.0.jar                            |Ambient World                 |ambient_world                 |1.3.0               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		lycanitesmobs-1.16.5-2.3.0.0.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.0.0      |DONE      |NOSIGNATURE
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |DONE      |NOSIGNATURE
		whisperwoods-1.16.5-2.0.1.jar                     |Whisperwoods                  |whisperwoods                  |2.0.1               |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		relics-0.1.14.jar                                 |Relics                        |relics                        |0.1.14              |DONE      |NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      |NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |NOSIGNATURE
		rats-7.2.0-1.16.5.jar                             |Rats                          |rats                          |7.2.0               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |DONE      |NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             |DONE      |NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |NOSIGNATURE
		HunterIllager-1.16.5-1.1.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.1.0        |DONE      |NOSIGNATURE
		[BETA]dannys_expansion1.16.5-1.0.9.1.jar          |Danny's Expansion             |dannys_expansion              |1.0.9               |DONE      |NOSIGNATURE
		byg-1.2.9.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.9               |DONE      |NOSIGNATURE
		enchantwithmob-1.16.5-1.4.6.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.4.6        |DONE      |NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      |NOSIGNATURE
		valhelsia_core-16.0.8.jar                         |Valhelsia Core                |valhelsia_core                |16.0.8              |DONE      |NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.1.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.1        |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.36.jar                  |GeckoLib                      |geckolib3                     |3.0.36              |DONE      |NOSIGNATURE
		dungeons_gear-1.16.5-3.0.17.jar                   |Dungeons Gear                 |dungeons_gear                 |3.0.17              |DONE      |NOSIGNATURE
	Crash Report UUID: c878c548-477f-4145-812b-abbef9539074
	Player Count: 1 / 8; [ServerPlayerEntity['f202k'/1754, l='ServerLevel[E]', x=-121.36, y=58.92, z=-100.40]]
	Data Packs: vanilla, mod:mowziesmobs (incompatible), mod:dungeonsmod, mod:pamhc2trees (incompatible), mod:cgm (incompatible), mod:jei, mod:timeless_and_classic, mod:conjurer_illager (incompatible), mod:dungeons_mobs (incompatible), mod:abnormals_core, mod:torohealth, mod:looot, mod:create, mod:bettercaves (incompatible), mod:modernlife, mod:citadel (incompatible), mod:alexsmobs, mod:artifacts, mod:untamedwilds (incompatible), mod:yungsapi, mod:additionalguns, mod:betteranimalsplus (incompatible), mod:mutantbeasts (incompatible), mod:guardvillagers, mod:outvoted, mod:iceandfire (incompatible), mod:waila, mod:gunswithoutroses (incompatible), mod:forge, mod:twilightforest, mod:subwild, mod:meetyourfight (incompatible), mod:betterendforge, mod:dsurround, mod:structure_gel, mod:dungeons_arise, mod:upgrade_aquatic, mod:pandoras_creatures (incompatible), mod:immersiveengineering, mod:greekfantasy, mod:experimental_m, mod:pamhc2crops (incompatible), mod:ambient_world, mod:pamhc2foodextended (incompatible), mod:lycanitesmobs, mod:cnb, mod:whisperwoods (incompatible), mod:curios, mod:relics, mod:spartanshields, mod:savageandravage, mod:rats, mod:ratlantis, mod:pamhc2foodcore (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:obfuscate (incompatible), mod:workshopsofdoom, mod:spartanweaponry, mod:hunterillager, mod:dannys_expansion, mod:byg, mod:enchantwithmob, mod:expandability, mod:valhelsia_core, mod:valhelsia_structures, mod:bettermineshafts, mod:geckolib3 (incompatible), mod:dungeons_gear
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by Gazer10** [comment]
Same, it's the Sunken Skeleton mob. I tried to disable spawning for it but it kept crashing near water.

[crash-2021-09-13_14.32.28-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7154112/crash-2021-09-13_14.32.28-server.txt)

**Comment by Patrigan** [comment]
It seems like your forge version is pretty old. 36.1.4 Can you try updating the version to at least 36.2.2?

**Comment by Patrigan** [comment]
Fixed in latest beta
