### ISSUE TITLE
Enchanter Crash

### ISSUE THREAD

**Issue by PhweeDev** [Thelnfamous1/Dungeons-Mobs#59]
Preparing crash report with UUID f013d5b5-529f-48cc-aa8c-37453ccb3ce5
[18:07:28] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.clearEntityMobEnchantments(EnchanterEntity.java:167) ~[dungeons_mobs:1.16.5-2.0.1-beta]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312]
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.remove(EnchanterEntity.java:161) ~[dungeons_mobs:1.16.5-2.0.1-beta]
	at net.minecraft.entity.Entity.func_70106_y(Entity.java:327) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70623_bb(MobEntity.java:640) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:388) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
[18:07:28] [Server thread/ERROR]: This crash report has been saved to: C:\Users\boele\AppData\Roaming\gdlauncher_next\instances\Raidcraft\..\..\instances\Raidcraft\crash-reports\crash-2022-01-30_18.07.28-server.txt
[18:07:28] [Server thread/INFO]: Stopping server
[18:07:28] [Server thread/INFO]: Saving players
[18:07:28] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/30/22 6:07 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.clearEntityMobEnchantments(EnchanterEntity.java:167) ~[dungeons_mobs:1.16.5-2.0.1-beta] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312] {}
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.remove(EnchanterEntity.java:161) ~[dungeons_mobs:1.16.5-2.0.1-beta] {re:classloading}
	at net.minecraft.entity.Entity.func_70106_y(Entity.java:327) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70623_bb(MobEntity.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:388) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:faction_craft.mixins.json:ServerWorldAccessor,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.clearEntityMobEnchantments(EnchanterEntity.java:167) ~[dungeons_mobs:1.16.5-2.0.1-beta] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312] {}
	at com.infamous.dungeons_mobs.entities.illagers.EnchanterEntity.remove(EnchanterEntity.java:161) ~[dungeons_mobs:1.16.5-2.0.1-beta] {re:classloading}
	at net.minecraft.entity.Entity.func_70106_y(Entity.java:327) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70623_bb(MobEntity.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:388) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:faction_craft.mixins.json:ServerWorldAccessor,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['JustPhwee'/1431, l='ServerLevel[New World]', x=-730.74, y=70.94, z=-450.34]]
	Chunk stats: ServerChunkCache: 2554
	Level dimension: minecraft:overworld
	Level spawn location: World: (-757,71,-527), Chunk: (at 11,4,1 in -48,-33; contains blocks -768,0,-528 to -753,255,-513), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 148769 game time, 132910 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 61008 (now: false), thunder time: 8652 (now: true)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1800775800 bytes (1717 MB) / 3724017664 bytes (3551 MB) up to 9067560960 bytes (8647 MB)
	CPUs: 4
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9728m -Xms9728m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.23
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.7+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      |Manifest: NOSIGNATURE
		dungeons_additions_test_6.jar                     |Dungeons Additions            |dungeonsadditions             |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Pirates_And_Looters_Kraken_Update.jar             |PiratesAndLootersReborn       |piratesandlootersreborn       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |Manifest: NOSIGNATURE
		dungeons_mobs-1.16.5-2.0.1-beta.jar               |Dungeons Mobs                 |dungeons_mobs                 |1.16.5-2.0.1-beta   |DONE      |Manifest: NOSIGNATURE
		chaosawakens-1.16.5-0.9.1.0-preview1.jar          |Chaos Awakens                 |chaosawakens                  |0.9.1.0-preview1    |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |DONE      |Manifest: NOSIGNATURE
		personality-1.16.5-1.0.3.jar                      |Personality                   |personality                   |1.0.3               |DONE      |Manifest: NOSIGNATURE
		looot-1.16.4-1.0.0.3.jar                          |Looot                         |looot                         |1.0.0.3             |DONE      |Manifest: NOSIGNATURE
		Cataclysm-0.11.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.2.0.jar                  |Savage & Ravage               |savageandravage               |3.2.0               |DONE      |Manifest: NOSIGNATURE
		ravageandcabbage-1.0.0.jar                        |Ravage & Cabbage              |ravageandcabbage              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		faction_craft-1.16.5-1.0.1.jar                    |Faction Craft                 |faction_craft                 |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |DONE      |Manifest: NOSIGNATURE
		workshopsofdoom-1.16.4-1.1.0.1.jar                |Workshops of Doom             |workshopsofdoom               |1.1.0.1             |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.16.5-1.4.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.4.0        |DONE      |Manifest: NOSIGNATURE
		renaissance_revolution_1.3.0_build8.jar           |Renaissance & Revolution      |renaissance__revolution       |Version 1.0.0       |DONE      |Manifest: NOSIGNATURE
		architectury-1.28.48.jar                          |Architectury                  |architectury                  |1.28.48             |DONE      |Manifest: NOSIGNATURE
		brazier-3.0.10-forge.jar                          |Brazier                       |brazier                       |3.0.10              |DONE      |Manifest: NOSIGNATURE
		ice_ice_baby-1.16.4-3.0.1.jar                     |Ice Ice Baby                  |ice_ice_baby                  |3.0.1               |DONE      |Manifest: NOSIGNATURE
		ColdsWanderingTrader(Forge1.16.5)vrs1.1.3.jar     |Colds Wandering Trader        |coldstrader                   |1.16.5-1.1.3        |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		catalogue-1.5.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.5.0               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.13.49-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.13.49             |DONE      |Manifest: NOSIGNATURE
		sodium-forge-2.9.10+rev.ea6353c.jar               |SodiumReforged                |sodium                        |2.9.10+rev.ea6353c  |DONE      |Manifest: NOSIGNATURE
		bettergolem-1.16.5-0.2.0.jar                      |Better Golem                  |bettergolem                   |1.16.5-0.2.0        |DONE      |Manifest: NOSIGNATURE
		illagers_plus-1.16.4v1.7.2.jar                    |Illagers+                     |illagers_plus                 |1.16.4v1.7.2        |DONE      |Manifest: NOSIGNATURE
		enchantwithmob-1.16.5-1.5.2.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.5.2        |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.0.5.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.5               |DONE      |Manifest: NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |DONE      |Manifest: NOSIGNATURE
		restored_earth-1.16.5-1.4.0.jar                   |Restored Earth                |restored_earth                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.23-universal.jar                |Forge                         |forge                         |36.2.23             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Tidbits-0.1.3.jar                                 |Tidbits                       |tidbits                       |0.1.2               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.65.jar                  |GeckoLib                      |geckolib3                     |3.0.65              |DONE      |Manifest: NOSIGNATURE
		dungeons_libraries-1.16.5-0.0.3-beta.jar          |Dungeons Libraries            |dungeons_libraries            |1.16.5-0.0.3-beta   |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |Manifest: NOSIGNATURE
		parrying-2.2.2.jar                                |Parrying                      |parrying                      |2.2.2               |DONE      |Manifest: NOSIGNATURE
		dungeons_gear-1.16.5-3.1.2-beta.jar               |Dungeons Gear                 |dungeons_gear                 |1.16.5-3.1.2-beta   |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f013d5b5-529f-48cc-aa8c-37453ccb3ce5
	Player Count: 1 / 8; [ServerPlayerEntity['JustPhwee'/1431, l='ServerLevel[New World]', x=-730.74, y=70.94, z=-450.34]]
	Data Packs: vanilla, mod:sodium (incompatible), mod:abnormals_core, mod:personality, mod:forge, mod:geckolib3 (incompatible), mod:ravageandcabbage, mod:waila, mod:jei, mod:faction_craft (incompatible), file/Illager Mania, mod:illagersweararmor (incompatible), mod:guardvillagers, mod:ice_ice_baby (incompatible), mod:hunterillager, mod:conjurer_illager (incompatible), mod:restored_earth (incompatible), mod:savageandravage, mod:structure_gel, mod:repurposed_structures, mod:morevillagers, mod:looot, mod:citadel (incompatible), mod:configured, mod:workshopsofdoom, mod:renaissance__revolution, mod:architectury, mod:catalogue, mod:cloth-config (incompatible), mod:bettergolem, mod:tidbits, mod:dungeons_libraries (incompatible), mod:parrying, mod:dungeonsadditions, mod:dungeons_mobs (incompatible), mod:chaosawakens, mod:coldstrader (incompatible), mod:dungeons_gear, mod:piratesandlootersreborn, mod:brazier, mod:enchantwithmob, mod:charm, mod:cataclysm (incompatible), mod:illagers_plus
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
[18:07:28] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# ..\..\instances\Raidcraft\crash-reports\crash-2022-01-30_18.07.28-server.txt

**Comment by BraveCaperCat** [comment]
You need to provide more info than that!
Such as:
Mod Version
MC Version
Crash log file (Not read out crash log)
Description of the issue
How to cause the issue

**Comment by Patrigan** [comment]
Enchanter fully disabled in latest version. Please use Enchant with Mob
